BepInEx/Il2CppInterop

UnhollowerBaseLib/ClassInjector.cs
UnhollowerBaseLib/Runtime/Il2CppStructs.cs
UnhollowerBaseLib/Runtime/VersionSpecific/Unity2018_0.cs
UnhollowerBaseLib/Runtime/VersionSpecific/Unity2018_4.cs
UnhollowerBaseLib/Runtime/VersionSpecific/Unity2019.cs

Revert class injector detour
Fix 2019 32 bit struct layout, change size from 192 to 188 bytes.
Fix 2018 32 bit struct layout, change cctor_thread from 4 bytes to 8 bytes.

Fix crash on 32 bit unity games

---

AssemblyUnhollower/AssemblyUnhollower.csproj
AssemblyUnhollower/DeobfuscationMapGenerator.cs
AssemblyUnhollower/MetadataAccess/CecilMetadataAccess.cs
AssemblyUnhollower/Program.cs
AssemblyUnhollower/UnhollowerOptions.cs

Makes it possible to use Il2cppDumper's output directly, also disables CLI mode as its not used in this fork

Make UnhollowerOptions.Source take AssemblyDefinitions directly

---

AssemblyUnhollower/AssemblyKnownImports.cs
AssemblyUnhollower/Contexts/RewriteGlobalContext.cs
AssemblyUnhollower/Passes/Pass19CopyMethodParameters.cs
AssemblyUnhollower/Passes/Pass80UnstripMethods.cs
UnhollowerBaseLib/Il2CppStructArray.cs

Generates wrapper methods with params attribute
Makes using stuff like imgui way easier

Add ParamArrayAttribute support

---

AssemblyUnhollower/Passes/Pass23GeneratePointerConstructors.cs

Change pointer constructor parameter name to match Il2CppObjectBase

---

UnhollowerBaseLib/ClassInjector.cs
UnhollowerBaseLib/MemoryUtils.cs

Implements a signature scanner to scan for premade signatures pointing to `Class::Init`.
Defaults to `il2cpp_class_has_references` if none of the signatures work.
*NOTE:* **il2cpp_class_has_references has a race condition with calling `Class::Init` but it will still allow games to run and inject their classes into il2cpp instead of failing like before**

Better Class::Init Search Method

---

UnhollowerBaseLib/ClassInjector.cs
UnhollowerBaseLib/Il2CppObjectBase.cs

Moved the Il2CppObjectBase constructor's behavior to `CreateGCHandle` so we are able to call it from the `CreateEmptyCtor` dynamic method as well.

Don't require IntPtr ctor for injected types

---

UnhollowerBaseLib/ClassInjector.cs
UnhollowerBaseLib/Il2CppObjectBase.cs

Fixes #19's issue which causes TryCast to fail if an IntPtr constructor is missing and modifies `CreateEmptyCtor` to not call the default constructor.

Fix TryCast and default constructor calling issues

---

UnhollowerBaseLib/Injection/ClassInjector.cs
UnhollowerBaseLib/Injection/EnumInjector.cs
UnhollowerBaseLib/Injection/InjectorHelpers.cs
UnhollowerRuntimeLib/Forwarders.cs

Method for injecting user-specified values into an existing il2cpp enum
Method for injecting managed enums into the il2cpp domain
Uses a managed way of pulling the il2cpp module's base address
Injected assembly and image now reside in InjectorHelpers
Injected type lookups and tokens now reside in InjectorHelpers
Hooks `Class::GetFieldDefaultValue` to support overriding field default values by bypassing il2cpp's metadata cache
Hooks `MetadataCache::GetTypeInfoFromTypeDefinitionIndex` as `Type::GetClass` uses it and it's necessary for creating enum arrays in the il2cpp runtime
Moved all existing hooks (except for `GenericMethod::GetMethod`) to InjectorHelpers
```cs
Il2CppSystem.Type fieldAttrType = Il2CppType.From(typeof(Il2CppSystem.Reflection.FieldAttributes));
Log("Before Modification: …
```

EnumInjector & Injection Refactor

---

UnhollowerBaseLib/Injection/ClassInjector.cs

To reproduce: Register a type like this in IL2CPP
```cs
using UnityEngine;
using System;
public class MyClass : MonoBehaviour
{
public MyClass(IntPtr ptr) : base(ptr)
{ }
public void BrokenMethod<T>(out T someParameter)
{
someParameter = default;
}
}
```
The cause is due to both checks for HideFromIl2CppAttribute don't include inherited types, and `ClassInjector::IsTypeSupported(Type)` incorrectly says that a type that is ByRef and whose element type is a GenericMethodParameter is valid.
This causes the following exception:
```
System.InvalidOperationException: Late bound operations cannot be performed on fields with types for which Type.ContainsGenericParameters is true.
at System.Reflection.RuntimeFieldInfo.CheckGeneric () [0x0000d] in <986ed57b9a8f4699a3c59a69eb05944a>:0
at …
```

[FIX] Methods that contain out parameters with generic type will fail to inject

---

UnhollowerBaseLib/Il2CppException.cs

From my testing, the API function `il2cpp_format_stack_trace` doesn't appear to return anything to the buffer and wrapping the Il2CppException to get the stack trace string returns 0x00. The only way to obtain the stack trace is to use the Il2CppSystem.Exception proxy from unhollowed libraries.

Dump Il2Cpp Exception stack traces from proxy class

---

UnhollowerBaseLib/Injection/InjectorHelpers.cs
UnhollowerBaseLib/Runtime/UnityVersionHandler.cs

The unity version in `UnityVersionHandler` is exposed to the UnhollowerBaseLib assembly (should it be a public get?)
A `GetIl2CppMethodPointer` helper is introduced in InjectorHelpers to help with obtaining proxy function method pointers.
The approach for obtaining GetTypeInfoFromDefinitionIndex pre v2018.3 is to look for the `RuntimeHelpers::InitializeArray` icall at `icalls/mscorlib/System.Runtime.CompilerServices/RuntimeHelpers.cpp` through xrefing the proxy that invokes it because `il2cpp_resolve_icall` doesn't contain libil2cpp icalls.
The same approach does appear to work for higher unity versions, but because this is the first time we approach looking for icalls like this I have decided to keep both ways of obtaining it.
`il2cpp_image_get_class` which is the entrypoint we use to …

Support pre v2018.3 in MetadataCache detours

---

UnhollowerBaseLib/Il2CppException.cs

The stacktrace of an Il2CppSystem.Exception instance doesn't give the full stacktrace of the exception. For example, a `System.Reflection.TargetInvocationException` has an inner stack trace for the exception that caused it. The inner exception is not provided from `StackTrace`, but can be gotten by using `ToString()` on the Exception Instance.

Rewrite IL2CPP Exception Stacktrace

---

Il2CppInterop.Runtime/Injection/InjectorHelpers.cs

This PR adds another method of resolving Class::GetDefaultFieldValue through an icall.
On some games the current method for resolving Class::GetDefaultFieldValue fails due to the compiler inlining some of the methods we traverse.
Relevant issue: BepInEx/BepInEx#479

Resolve Class::GetDefaultFieldValue through ICall

---

Il2CppInterop.HarmonySupport/Il2CppDetourMethodPatcher.cs
Il2CppInterop.Runtime/DelegateSupport.cs
Il2CppInterop.Runtime/Il2CppInterop.Runtime.csproj
Il2CppInterop.Runtime/Injection/ClassInjector.cs
Il2CppInterop.Runtime/Injection/TrampolineHelpers.cs

Currently HarmonySupport and ClassInjector do the same thing but differently leading to issues on x32. This PR fixes injecting methods that use structs on 32 bit.

Merge ConvertManagedTypeToIL2CPPType and NativeType

---

.gitignore
Il2CppInterop.CLI/Program.cs
Il2CppInterop.Generator/Extensions/StringEx.cs
Il2CppInterop.Generator/GeneratorOptions.cs
Il2CppInterop.Generator/Il2CppInterop.Generator.csproj

Game developers often use the global namespace and external libraries when making their games. For modding, this can cause conflicts during mod development. Although we currently have a way to prefix assemblies and namespaces, it's an opt-in system. An opt-out solution would be better because mod loaders can't anticipate all the assemblies game communities might want to prefix. By prefixing everything but UnityEditor and UnityEngine, we can prevent all potential conflicts between generated interop and managed libraries.

Prefix Almost Everything

---

Il2CppInterop.Runtime/IL2CPP.cs
Il2CppInterop.Runtime/InteropTypes/Il2CppObjectBase.cs

Use a cached DynamicMethod instead reflection for instantiating il2cpp objects.
Cursed `Unsafe.As`s are required because there is no way to ignore generic constraints and `PointerToValueGeneric` can return value types.

Improve Cast and PointerToValueGeneric performance

---

Il2CppInterop.Runtime/Injection/DetourProvider.cs
Il2CppInterop.Runtime/Injection/InjectorHelpers.cs

Assigns the trampoline before applying the detour so there are never any nulls.
Unfortunately this is a breaking change because we need to add the `GenerateTrampoline` to `IDetour`, but because afaik BepInEx is the only consumer of that api we could just overlook it?

Get rid of the Thread.Sleep(1) workaround in InjectorHelpers

---

Il2CppInterop.Runtime/Injection/InjectorHelpers.cs

Mask out the byte that sets the stack size - it's been observed to be both 0x20 and 0x40

Update sig scan for Class::GetFieldDefaultValue

---

Il2CppInterop.Generator/Passes/Pass79UnstripTypes.cs

On some Unity versions, some types will have layout attributes assigned to them even though they are not of ValueType.
A prime example is `UnityEngine.LightProbes` inside `UnityEngine.CoreModule.dll` on 2018.4.36f1 ([TestGame](https://github.com/BepInEx/TestGame/suites/8775722868/artifacts/398337413)).
This went unnoticed for a while until we switched to CoreCLR which is way stricter in terms of type loading.

Ensure Proper Layout for Non-ValueTypes

---

Il2CppInterop.Generator/Extensions/CustomAttributeEx.cs
Il2CppInterop.Generator/Passes/Pass11ComputeTypeSpecifics.cs
Il2CppInterop.Generator/Passes/Pass21GenerateValueTypeFields.cs

Workarounds https://github.com/SamboyCoding/Cpp2IL/issues/167 by marking structs with fields that would crash the runtime as non-blittable

Workaround garbage field offset values

---

Il2CppInterop.Runtime/Injection/InjectorHelpers.cs

This fixes FindGetTypeInfoFromTypeDefinitionIndex for Unity games built with C++ Compiler Configuration "Master" for IL2CPP (The Long Dark for example).
I'm not sure if this is IL2CPP Metadata v29 specific, but since we've only seen The Long Dark with this issue I'm assuming it's an v29 occasion only.

Fix FindGetTypeInfoFromTypeDefinitionIndex for Unity games built with IL2CPP Master

---

Il2CppInterop.Common/XrefScans/XrefScannerLowLevel.cs
Il2CppInterop.Runtime/Injection/InjectorHelpers.cs

This should not be a breaking change, I thought of a better way of doing it

Fix GenericMethod::GetMethod search for IL2CPP Master games

---

Il2CppInterop.Generator/Passes/Pass10CreateTypedefs.cs

* `<PrivateImplementationDetails>` should be Il2Cpp namespace prefixed.
* Revised the definition for injected Cpp2IL types to include any type whose namespace starts with Cpp2ILInjected.
* For example, using the `callanalyzer` processing layer produces types in the `Cpp2ILInjected.CallAnalysis` namespace.

Small tweaks to the CreateTypedefs pass

---

Il2CppInterop.Runtime/Injection/ClassInjector.cs

This PR fixes an issue where calling injected methods via Il2Cpp reflection resulted in garbage data for value types and null for reference types returned.
This issue is caused by change in signature of invoker_method in Il2Cpp version 29

Fix invalid return value when calling injected methods via Il2Cpp reflection

---

Il2CppInterop.Runtime/Injection/ClassInjector.cs
Il2CppInterop.Runtime/Runtime/VersionSpecific/MethodInfo/Interfaces.cs
Il2CppInterop.Runtime/Runtime/VersionSpecific/MethodInfo/MethodInfo_16_0.cs
Il2CppInterop.Runtime/Runtime/VersionSpecific/MethodInfo/MethodInfo_21_0.cs
Il2CppInterop.Runtime/Runtime/VersionSpecific/MethodInfo/MethodInfo_24_0.cs
Il2CppInterop.Runtime/Runtime/VersionSpecific/MethodInfo/MethodInfo_24_1.cs
Il2CppInterop.Runtime/Runtime/VersionSpecific/MethodInfo/MethodInfo_29_0.cs
Il2CppInterop.Runtime/Runtime/VersionSpecific/MethodInfo/MethodInfo_29_1.cs
Il2CppInterop.StructGenerator/Il2CppStructWrapperGenerator.cs
Il2CppInterop.StructGenerator/TypeGenerators/Il2CppMethodInfoGenerator.cs
Il2CppInterop.StructGenerator/VersionSpecificGenerator.cs

This PR fixes that calling delegate `Invoke()` method caused a crash on il2cpp version 29 or higher.
This issue is caused by a new field in the `MethodInfo` class called `virtualMethodPointer`. Now when calling delegates il2cpp uses it to determine what to call. Since Il2CppInterop was not aware of that, it's value was null thus causing the crash.
I'm not entirely sure if it's supposed to have a value of it's own though. I have checked with a type from my game and every method there had `virtualMethodPointer` field equal to `methodPointer` field.
I have tested this on Unity 2021.3.14, il2cpp 29: no crashes calling delegates or UnityEvent's

Fix crash calling delegate invoke on il2cpp 29 or higher

---

Il2CppInterop.Generator/Extensions/ILGeneratorEx.cs
Il2CppInterop.Generator/Passes/Pass50GenerateMethods.cs
Il2CppInterop.Runtime/IL2CPP.cs

Adds support for byref generic parameters in methods, e.g. `Il2CppSystem.Collections.Dictionary.TryGetValue(TKey key, out TValue value)`
Closes #73

Add support for byref generic parameters in methods

---

Il2CppInterop.Runtime/Injection/ClassInjector.cs
Il2CppInterop.Runtime/Injection/Hook.cs
Il2CppInterop.Runtime/Injection/Hooks/Class_FromIl2CppType_Hook.cs
Il2CppInterop.Runtime/Injection/Hooks/Class_FromName_Hook.cs
Il2CppInterop.Runtime/Injection/Hooks/Class_GetFieldDefaultValue_Hook.cs
Il2CppInterop.Runtime/Injection/Hooks/GenericMethod_GetMethod_Hook.cs
Il2CppInterop.Runtime/Injection/Hooks/MetadataCache_GetTypeInfoFromTypeDefinitionIndex_Hook.cs
Il2CppInterop.Runtime/Injection/InjectorHelpers.cs

This PR improves the way hooks are done. Now a hook is created by implementing Hook class. The only things that need to be defined are the hook delegate, hook method and find target method function. 
This removes some boilerplate code, and splits hooks across files for more modularity.
No functional changes. Tested on Core Keeper 2021.3.14f

Refactor hook creation

---

Il2CppInterop.Common/XrefScans/XrefScannerLowLevel.cs
Il2CppInterop.Generator/Extensions/ILGeneratorEx.cs
Il2CppInterop.Generator/Passes/Pass50GenerateMethods.cs
Il2CppInterop.Generator/Utils/FieldAccessorGenerator.cs
Il2CppInterop.Generator/Utils/UnstripGenerator.cs

Fixes an issue where non-blittable generic value types get unboxed when they shouldn't be during parameter loading. 
The most notable example is adding a boxed integer into a dictionary, the value field would have invalid data written to it.
```cs
private unsafe void Test() {
long testLong = 2137;
var testInt64 = new Il2CppSystem.Int64();
*&testInt64.m_value = testLong;
var dictionary = new Il2CppSystem.Collections.Generic.Dictionary<string, Il2CppSystem.Object>();
dictionary.Add("test", testInt64.BoxIl2CppObject()); // PREV: Writes invalid data to value field
foreach (var kv in dictionary)
{
Log.LogInfo(kv.Key);   // "test"
Log.LogInfo(kv.Value); // 2137   (PREV: crash on access)
}
}
```

Don't unbox non-blittable generic valuetypes for parameter loading

---

Il2CppInterop.Runtime/Injection/Hooks/GenericMethod_GetMethod_Hook.cs
Il2CppInterop.Runtime/Runtime/UnityVersionHandler.cs

This PR fixes a crash after call to `GenericMethod::GetMethod()` hook. 
This issue appears on Unity version 2020.3.41+, and in some cases in 2021.3.12+, 2022.1.23+ because of this [fix](https://issuetracker.unity3d.com/issues/il2cpp-build-crashes-when-symbols-cannot-be-found)
In these versions `Object::GetVirtualMethod()` calls `GenericMethod::GetGenericVirtualMethod()` instead of `GenericMethod::GetMethod()`
This also has an annoying interaction with shims added in 2021.2.0, where they get inlined together. 
I also removed `targetTargets.Length == 1` check because it seems to be always true, due to early return in `GenericMethod::GetMethod()`  that I noticed. Unfortunately because of this, problems on debug builds could emerge. I don't know if these are important though.
Tested on a …

Fix GenericMethod_GetMethod_Hook on Unity 2020.3.41+

---

Il2CppInterop.HarmonySupport/HarmonyBackendComponent.cs
Il2CppInterop.Runtime/DelegateSupport.cs
Il2CppInterop.Runtime/Injection/ClassInjector.cs
Il2CppInterop.Runtime/InteropTypes/Fields/Il2CppReferenceField.cs

This PR combines a number of small fixes:
1. Fix inherited injected fields not being initialized on derived classes
2. Fix errors injecting a type inheriting a abstract type. I'm not entirely sure why this happens, but the `baseVTablePointer[i].method` in my case was not default, even though all of it's fields were null.
3. Fix delegate type names including assembly names. This might cause very long names and if such name becomes too long (I think 1024 characters or more), the runtime will not like it.
4. Fix NRE setting null to `Value` of `Il2CppReferenceField`.
5. Fix Il2Cpp Detour not being applied if target type is a struct. I have tested this change and it does not cause any issues. Patches get called correctly, and `ref MyStruct __instance` injection works correctly.
I have tested …

Small fixes

---

Il2CppInterop.Runtime/IL2CPP.cs

it fixed the System.AccessViolationException protected memory error in some games

Changed to LPUTF8Str to fix Obfuscated Class and Field Problems

---

Il2CppInterop.Generator/Contexts/MethodRewriteContext.cs
Il2CppInterop.Generator/Passes/Pass70GenerateProperties.cs

This means that when there are two types in the same namespace that have properties or methods with the same name, trying to rename them will work as intended (like fields).
~~This change is 'breaking', though considering this issue meant property renaming was completely broken makes me think that nobody will be impacted.~~ Now checking for both

Account for type name when renaming properties and methods from the deobf map

---

Il2CppInterop.Runtime/InteropTypes/Arrays/Il2CppArrayBase.cs

This will be important for unstripping `ldlen`.

Create a non-generic Il2CppArrayBase class

---

Il2CppInterop.Runtime/Injection/ClassInjector.cs

The class injector does checking on abstract methods to match parameter names and types of implemented methods, but the ParameterInfo struct and hence the name field was removed in newer versions of IL2CPP. This is an easy fix because the IL2CPP API has a method to get the name of a parameter from the MethodInfo and index.

Fix class injector abstract method handling

---

Il2CppInterop.Generator/Contexts/MethodRewriteContext.cs
Il2CppInterop.Generator/Extensions/AsmResolverExtensions.cs
Il2CppInterop.Generator/Passes/Pass13FillGenericConstraints.cs
Il2CppInterop.Generator/Passes/Pass80UnstripMethods.cs

Previously:
```cs
public class AdapterView<T, VH, T_AXIS_LIST> : MonoBehaviour
where VH : ViewHolder<T>
where T_AXIS_LIST : IL2CppSystem.Enum
{
}
```
Now:
```cs
public class AdapterView<T, VH, T_AXIS_LIST> : MonoBehaviour
where VH : ViewHolder<T>
where T_AXIS_LIST : System.Enum
{
}
```

Special-case System.Enum as a generic constraint

---

Il2CppInterop.Generator/Passes/Pass80UnstripMethods.cs

* Support PinnedTypeSignature
* Support CustomModifierTypeSignature
* Resolve nested types with the correct priority

Improve type resolution for unstripping

---

Il2CppInterop.Generator/Utils/UnstripTranslator.cs

I don't have an example of this happening, but I know that it could.

Expand Macros Before Unstripping

---

Il2CppInterop.Generator/Contexts/MethodRewriteContext.cs
Il2CppInterop.Generator/Contexts/RewriteGlobalContext.cs
Il2CppInterop.Generator/Passes/Pass12FillTypedefs.cs

Fix Invalid Generic Parameter Names

---

Il2CppInterop.Generator/Passes/Pass22GenerateEnums.cs

Prevent null strings in OriginalName

---

Il2CppInterop.Generator/Passes/Pass19CopyMethodParameters.cs

Fix null ParameterDefinition when copying

---

Il2CppInterop.Generator/Contexts/FieldRewriteContext.cs
Il2CppInterop.Generator/Contexts/MethodRewriteContext.cs
Il2CppInterop.Generator/Contexts/RewriteGlobalContext.cs
Il2CppInterop.Generator/Extensions/StringEx.cs
Il2CppInterop.Generator/Il2CppInterop.Generator.csproj
Il2CppInterop.Generator/Passes/Pass10CreateTypedefs.cs
Il2CppInterop.Generator/Passes/Pass12FillTypedefs.cs
Il2CppInterop.Generator/Passes/Pass80UnstripMethods.cs

Cleanup name validity

---

Il2CppInterop.Generator/Contexts/AssemblyRewriteContext.cs
Il2CppInterop.Generator/Contexts/RewriteGlobalContext.cs
Il2CppInterop.Generator/Passes/Pass16ScanMethodRefs.cs
Il2CppInterop.Generator/Passes/Pass81FillUnstrippedMethodBodies.cs
Il2CppInterop.Generator/Runners/InteropAssemblyGenerator.cs

Fixed some static collections holding up to multiple GBs of MethodDefinitions without ever being reset.

Major generator memory leak fix

---

Il2CppInterop.Generator/Contexts/RewriteGlobalContext.cs
Il2CppInterop.Generator/Il2CppInterop.Generator.csproj
Il2CppInterop.Generator/Passes/Pass61ImplementAwaiters.cs
Il2CppInterop.Generator/Runners/InteropAssemblyGenerator.cs

Adds `Pass61ImplementAwaiters`
Looks for types implementing `INotifyCompletion` and generates new methods that allow the interop types to implement that interface, calling the Il2CppSystem.Action -> System.Action implicit conversion before calling the original method.
This makes originally-awaitable types (e.g. `UniTask`s, if the game has them) awaitable again.
I previously did this in a much less automated way with Cecil in another project, but the runtime didn't like what I was doing, so I figured I'd make it less janky and add it to Il2CppInterop, and sure enough the runtime no longer rejects the type.

Add awaiter implementation

---

Il2CppInterop.Generator/Contexts/AssemblyRewriteContext.cs
Il2CppInterop.Generator/Contexts/RewriteGlobalContext.cs
Il2CppInterop.Generator/Contexts/TypeRewriteContext.cs
Il2CppInterop.Generator/Extensions/AsmResolverExtensions.cs
Il2CppInterop.Generator/Extensions/ILGeneratorEx.cs
Il2CppInterop.Generator/Extensions/TypeReferenceEx.cs
Il2CppInterop.Generator/Passes/Pass05CreateRenameGroups.cs
Il2CppInterop.Generator/Passes/Pass21GenerateValueTypeFields.cs
Il2CppInterop.Generator/Passes/Pass50GenerateMethods.cs
Il2CppInterop.Generator/Passes/Pass79UnstripTypes.cs
Il2CppInterop.Generator/Passes/Pass80UnstripMethods.cs
Il2CppInterop.Generator/Utils/FieldAccessorGenerator.cs
Il2CppInterop.Generator/Utils/UnstripGenerator.cs

This is what you get when you ask a person completely unfamiliar with a complex codebase to submit a PR.
As discussed in #211 I've tested that the code generated for one particular method I was having problem is now fine. I have no slightest idea, if this `IsValueType` matters elsewhere. For, example when a value of this type is passed as a method parameter. I also do not know how to find or test relevant code paths.
IMO, this change is unlikely to break anything already not broken, but this may be not a comprehensive fix. I briefly considered patching this at run-time in AsmResolver using reflections, but this is going to be complex because this is not a field you can change the value off, it actually checks the binary metadata when you call this property, so you would need to patch …

AsmResolver System.Enum IsValueType=true workaround. Fixes #211

---

Il2CppInterop.Generator/Passes/Pass90WriteToDisk.cs

Pass 90 would import the TargetFrameworkAttribute after the corlib refs fixup, which would result in a single remaining direct System.Private.CorLib reference.

Fix Pass 90 imports TargetFrameworkAttribute after corlib refs fixup

---

Il2CppInterop.Runtime/Injection/ClassInjector.cs

Support prefixed types in ClassInjector.SystemTypeFromIl2CppType
